# Generated by Django 5.0 on 2025-04-30 11:29

import docteur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='doc_profile_pics/photo_defaut.jpg', null=True, upload_to=docteur.models.Doctor.doctor_photo_path, verbose_name='Photo de profil')),
                ('workplace_type', models.CharField(blank=True, choices=[('privé', 'Privé'), ('hopital', 'Hopital'), ('clinique', 'Clinique')], max_length=20, null=True, verbose_name='Type de lieu de travail')),
                ('workplace_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du lieu de travail')),
                ('experience_years', models.IntegerField(default=0, verbose_name="Années d'expérience")),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spécialisation détaillée')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Frais de consultation')),
                ('availability_dim', models.TextField(blank=True, null=True, verbose_name='Disponibilité dimanche')),
                ('availability_lun', models.TextField(blank=True, null=True, verbose_name='Disponibilité lundi')),
                ('availability_mar', models.TextField(blank=True, null=True, verbose_name='Disponibilité mardi')),
                ('availability_mer', models.TextField(blank=True, null=True, verbose_name='Disponibilité mercredi')),
                ('availability_jeu', models.TextField(blank=True, null=True, verbose_name='Disponibilité jeudi')),
                ('availability_ven', models.TextField(blank=True, null=True, verbose_name='Disponibilité vendredi')),
                ('availability_sam', models.TextField(blank=True, null=True, verbose_name='Disponibilité samedi')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('social_media', models.JSONField(blank=True, null=True, verbose_name='Réseaux sociaux (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
