# Generated by Django 5.2.1 on 2025-05-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_typing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
