# Generated by Django 5.0 on 2025-05-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_type',
            field=models.CharField(choices=[('doctor_doctor', 'Docteur - Docteur'), ('doctor_patient', 'Docteur - Patient')], default='doctor_patient', max_length=20),
        ),
    ]
