# Generated by Django 5.0 on 2025-04-30 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='ficheclinique',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_cliniques', to='patient.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('first_name', 'last_name', 'birth_date')},
        ),
    ]
