# Generated by Django 5.0 on 2025-05-08 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0002_initial'),
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Confirmé', 'Confirmé'), ('En attente', 'En attente'), ('Annulé', 'Annulé')], default='En attente', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_confirme', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='docteur.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patient.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
