# Generated by Django 5.0 on 2025-05-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='origine',
            field=models.CharField(choices=[('Manuel', 'Ajout manuel'), ('Dossier médical', 'Créé depuis un dossier médical'), ('Autre', 'Autre origine')], default='Manuel', max_length=50, verbose_name='Origine du rendez-vous'),
        ),
    ]
