# Generated by Django 5.0 on 2025-05-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rendezvous_origine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalImage',
        ),
    ]
