# Generated by Django 5.0 on 2025-04-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='ablation_fils',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='angio',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='bouchons_lacrym',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='cataracte',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='cataracte_type',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='ce',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='conjonctivite',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='conjonctivite_type',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_ablation_fils',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_angio',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_bouchons_lacrym',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_ce',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_echo_a',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_echo_b',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_fo',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_laser_argon',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_laser_yag',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_lentille_therap',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_scjr',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_skiascopie',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_v3m',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='description_vi',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diabetique',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='echo_a',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='echo_b',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='file',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='fo',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='glaucome',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='glaucome_type',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='hypertendu',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='keratoconique',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='laser_argon',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='laser_yag',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lentille_rpg',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lentille_sclerale',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lentille_souple',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lentille_souple_spherique',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lentille_souple_torique',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lentille_therap',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lrpg_bitorique',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lrpg_spherique',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lrpg_torique_ant',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lrpg_torique_post',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='prochain_rendez_vous',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='scjr',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='sclerose',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='sclerose_type',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='skiascopie',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='stade_keratoconique',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='uveite',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='uveite_type',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='v3m',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='vi',
        ),
        migrations.CreateModel(
            name='DescriptionGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_records/%Y/%m/%d/')),
                ('diabetique', models.BooleanField(default=False, verbose_name='Diabétique')),
                ('keratoconique', models.BooleanField(default=False, verbose_name='Kératoconique')),
                ('stade_keratoconique', models.CharField(blank=True, choices=[('fruste', 'Kératocône fruste'), ('stade_1', 'Stade 1'), ('stade_2', 'Stade 2'), ('stade_3', 'Stade 3'), ('stade_4', 'Stade 4')], max_length=10, verbose_name='Stade du kératoconique')),
                ('cataracte', models.BooleanField(default=False, verbose_name='Cataracte')),
                ('cataracte_type', models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('nucléaire', 'Cataracte nucléaire'), ('corticale', 'Cataracte corticale'), ('sous-capsulaire postérieure', 'Cataracte sous-capsulaire postérieure'), ('congénitale', 'Cataracte congénitale'), ('traumatique', 'Cataracte traumatique'), ('secondaire', 'Cataracte secondaire')], max_length=200, verbose_name='Type de cataracte')),
                ('glaucome', models.BooleanField(default=False, verbose_name='Glaucome')),
                ('glaucome_type', models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('angle_ouvert', 'Glaucome à angle ouvert'), ('angle_ferme', 'Glaucome à angle fermé')], max_length=20, verbose_name='Type de glaucome')),
                ('uveite', models.BooleanField(default=False, verbose_name='Uvéite')),
                ('uveite_type', models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('anterieure', 'Uvéite antérieure'), ('intermediaire', 'Uvéite intermédiaire'), ('posterieure', 'Uvéite postérieure'), ('panuveite', 'Panuvéite')], max_length=20, verbose_name="Type d'uvéite")),
                ('conjonctivite', models.BooleanField(default=False, verbose_name='Conjonctivite')),
                ('conjonctivite_type', models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('bacterienne', 'Conjonctivite bactérienne'), ('virale', 'Conjonctivite virale'), ('allergique', 'Conjonctivite allergique'), ('irritative', 'Conjonctivite irritative'), ('toxique', 'Conjonctivite toxique'), ('autoimmune', 'Conjonctivite auto-immune'), ('neonatale', 'Conjonctivite néonatale')], max_length=20, verbose_name='Type de conjonctivite')),
                ('sclerose', models.BooleanField(default=False, verbose_name='Sclérose')),
                ('sclerose_type', models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('anterieure', 'Sclérite antérieure'), ('posterieure', 'Sclérite postérieure'), ('episclerite', 'Épisclérite'), ('nodulaire', 'Sclérite nodulaire'), ('necrosante_inflammation', 'Sclérite nécrosante avec inflammation'), ('necrosante_sans_inflammation', 'Sclérite nécrosante sans inflammation (scléromalacie perforante)')], max_length=30, verbose_name='Type de sclérose')),
                ('hypertendu', models.BooleanField(default=False, verbose_name='Hypertendu')),
                ('v3m', models.BooleanField(default=False, verbose_name='V3M')),
                ('description_v3m', models.TextField(blank=True, verbose_name='Description V3M')),
                ('fo', models.BooleanField(default=False, verbose_name='F.O')),
                ('description_fo', models.TextField(blank=True, verbose_name='Description F.O')),
                ('ce', models.BooleanField(default=False, verbose_name='C.E')),
                ('description_ce', models.TextField(blank=True, verbose_name='Description C.E')),
                ('scjr', models.BooleanField(default=False, verbose_name='S/Cj -R/B')),
                ('description_scjr', models.TextField(blank=True, verbose_name='Description S/Cj -R/B')),
                ('vi', models.BooleanField(default=False, verbose_name='V.I')),
                ('description_vi', models.TextField(blank=True, verbose_name='Description V.I')),
                ('ablation_fils', models.BooleanField(default=False, verbose_name='Ablation de Fils')),
                ('description_ablation_fils', models.TextField(blank=True, verbose_name='Description Ablation de Fils')),
                ('echo_a', models.BooleanField(default=False, verbose_name='Echo A')),
                ('description_echo_a', models.TextField(blank=True, verbose_name='Description Echo A')),
                ('echo_b', models.BooleanField(default=False, verbose_name='Echo B')),
                ('description_echo_b', models.TextField(blank=True, verbose_name='Description Echo B')),
                ('skiascopie', models.BooleanField(default=False, verbose_name='Skiascopie')),
                ('description_skiascopie', models.TextField(blank=True, verbose_name='Description Skiascopie')),
                ('laser_argon', models.BooleanField(default=False, verbose_name='Laser Argon')),
                ('description_laser_argon', models.TextField(blank=True, verbose_name='Description Laser Argon')),
                ('laser_yag', models.BooleanField(default=False, verbose_name='Laser YAG')),
                ('description_laser_yag', models.TextField(blank=True, verbose_name='Description Laser YAG')),
                ('angio', models.BooleanField(default=False, verbose_name='Angio')),
                ('description_angio', models.TextField(blank=True, verbose_name='Description Angio')),
                ('lentille_therap', models.BooleanField(default=False, verbose_name='Lentille Therap')),
                ('description_lentille_therap', models.TextField(blank=True, verbose_name='Description Lentille Therap')),
                ('bouchons_lacrym', models.BooleanField(default=False, verbose_name='Bouchons Lacrym')),
                ('description_bouchons_lacrym', models.TextField(blank=True, verbose_name='Description Bouchons Lacrym')),
                ('prochain_rendez_vous', models.DateField(blank=True, null=True, verbose_name='Prochain rendez-vous')),
                ('lentille_souple', models.BooleanField(default=False, verbose_name='Lentille souple')),
                ('lentille_souple_spherique', models.BooleanField(default=False, verbose_name='Lentille souple sphérique')),
                ('lentille_souple_torique', models.BooleanField(default=False, verbose_name='Lentille souple torique')),
                ('lentille_rpg', models.BooleanField(default=False, verbose_name='Lentille RPG')),
                ('lrpg_spherique', models.BooleanField(default=False, verbose_name='LRPG sphérique')),
                ('lrpg_torique_ant', models.BooleanField(default=False, verbose_name='LRPG torique face antérieure')),
                ('lrpg_torique_post', models.BooleanField(default=False, verbose_name='LRPG torique face postérieure')),
                ('lrpg_bitorique', models.BooleanField(default=False, verbose_name='LRPG bi-torique')),
                ('lentille_sclerale', models.BooleanField(default=False, verbose_name='Lentille sclérale')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description_generale', to='records.medicalrecord')),
            ],
        ),
    ]
