# Generated by Django 5.0 on 2025-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_medicalimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='ablation_fils',
            field=models.BooleanField(default=False, verbose_name='Ablation de Fils'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='angio',
            field=models.BooleanField(default=False, verbose_name='Angio'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='bouchons_lacrym',
            field=models.BooleanField(default=False, verbose_name='Bouchons Lacrym'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='cataracte',
            field=models.BooleanField(default=False, verbose_name='Cataracte'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='cataracte_type',
            field=models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('nucléaire', 'Cataracte nucléaire'), ('corticale', 'Cataracte corticale'), ('sous-capsulaire postérieure', 'Cataracte sous-capsulaire postérieure'), ('congénitale', 'Cataracte congénitale'), ('traumatique', 'Cataracte traumatique'), ('secondaire', 'Cataracte secondaire')], max_length=200, verbose_name='Type de cataracte'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ce',
            field=models.BooleanField(default=False, verbose_name='C.E'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='conjonctivite',
            field=models.BooleanField(default=False, verbose_name='Conjonctivite'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='conjonctivite_type',
            field=models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('bacterienne', 'Conjonctivite bactérienne'), ('virale', 'Conjonctivite virale'), ('allergique', 'Conjonctivite allergique'), ('irritative', 'Conjonctivite irritative'), ('toxique', 'Conjonctivite toxique'), ('autoimmune', 'Conjonctivite auto-immune'), ('neonatale', 'Conjonctivite néonatale')], max_length=20, verbose_name='Type de conjonctivite'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_ablation_fils',
            field=models.TextField(blank=True, verbose_name='Description Ablation de Fils'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_angio',
            field=models.TextField(blank=True, verbose_name='Description Angio'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_bouchons_lacrym',
            field=models.TextField(blank=True, verbose_name='Description Bouchons Lacrym'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_ce',
            field=models.TextField(blank=True, verbose_name='Description C.E'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_echo_a',
            field=models.TextField(blank=True, verbose_name='Description Echo A'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_echo_b',
            field=models.TextField(blank=True, verbose_name='Description Echo B'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_fo',
            field=models.TextField(blank=True, verbose_name='Description F.O'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_generale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_laser_argon',
            field=models.TextField(blank=True, verbose_name='Description Laser Argon'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_laser_yag',
            field=models.TextField(blank=True, verbose_name='Description Laser YAG'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_lentille_therap',
            field=models.TextField(blank=True, verbose_name='Description Lentille Therap'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_scjr',
            field=models.TextField(blank=True, verbose_name='Description S/Cj -R/B'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_skiascopie',
            field=models.TextField(blank=True, verbose_name='Description Skiascopie'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_v3m',
            field=models.TextField(blank=True, verbose_name='Description V3M'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_vi',
            field=models.TextField(blank=True, verbose_name='Description V.I'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diabetique',
            field=models.BooleanField(default=False, verbose_name='Diabétique'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='echo_a',
            field=models.BooleanField(default=False, verbose_name='Echo A'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='echo_b',
            field=models.BooleanField(default=False, verbose_name='Echo B'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='fo',
            field=models.BooleanField(default=False, verbose_name='F.O'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='glaucome',
            field=models.BooleanField(default=False, verbose_name='Glaucome'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='glaucome_type',
            field=models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('angle_ouvert', 'Glaucome à angle ouvert'), ('angle_ferme', 'Glaucome à angle fermé')], max_length=20, verbose_name='Type de glaucome'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='hypertendu',
            field=models.BooleanField(default=False, verbose_name='Hypertendu'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='keratoconique',
            field=models.BooleanField(default=False, verbose_name='Kératoconique'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='laser_argon',
            field=models.BooleanField(default=False, verbose_name='Laser Argon'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='laser_yag',
            field=models.BooleanField(default=False, verbose_name='Laser YAG'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lentille_rpg',
            field=models.BooleanField(default=False, verbose_name='Lentille RPG'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lentille_sclerale',
            field=models.BooleanField(default=False, verbose_name='Lentille sclérale'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lentille_souple',
            field=models.BooleanField(default=False, verbose_name='Lentille souple'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lentille_souple_spherique',
            field=models.BooleanField(default=False, verbose_name='Lentille souple sphérique'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lentille_souple_torique',
            field=models.BooleanField(default=False, verbose_name='Lentille souple torique'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lentille_therap',
            field=models.BooleanField(default=False, verbose_name='Lentille Therap'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lrpg_bitorique',
            field=models.BooleanField(default=False, verbose_name='LRPG bi-torique'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lrpg_spherique',
            field=models.BooleanField(default=False, verbose_name='LRPG sphérique'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lrpg_torique_ant',
            field=models.BooleanField(default=False, verbose_name='LRPG torique face antérieure'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lrpg_torique_post',
            field=models.BooleanField(default=False, verbose_name='LRPG torique face postérieure'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prochain_rendez_vous',
            field=models.DateField(blank=True, null=True, verbose_name='Prochain rendez-vous'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='scjr',
            field=models.BooleanField(default=False, verbose_name='S/Cj -R/B'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='sclerose',
            field=models.BooleanField(default=False, verbose_name='Sclérose'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='sclerose_type',
            field=models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('anterieure', 'Sclérite antérieure'), ('posterieure', 'Sclérite postérieure'), ('episclerite', 'Épisclérite'), ('nodulaire', 'Sclérite nodulaire'), ('necrosante_inflammation', 'Sclérite nécrosante avec inflammation'), ('necrosante_sans_inflammation', 'Sclérite nécrosante sans inflammation (scléromalacie perforante)')], max_length=30, verbose_name='Type de sclérose'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='skiascopie',
            field=models.BooleanField(default=False, verbose_name='Skiascopie'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='stade_keratoconique',
            field=models.CharField(blank=True, choices=[('fruste', 'Kératocône fruste'), ('stade_1', 'Stade 1'), ('stade_2', 'Stade 2'), ('stade_3', 'Stade 3'), ('stade_4', 'Stade 4')], max_length=10, verbose_name='Stade du kératoconique'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='uveite',
            field=models.BooleanField(default=False, verbose_name='Uvéite'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='uveite_type',
            field=models.CharField(blank=True, choices=[('', '-- Sélectionner --'), ('anterieure', 'Uvéite antérieure'), ('intermediaire', 'Uvéite intermédiaire'), ('posterieure', 'Uvéite postérieure'), ('panuveite', 'Panuvéite')], max_length=20, verbose_name="Type d'uvéite"),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='v3m',
            field=models.BooleanField(default=False, verbose_name='V3M'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vi',
            field=models.BooleanField(default=False, verbose_name='V.I'),
        ),
        migrations.DeleteModel(
            name='DescriptionGenerale',
        ),
    ]
